### ISSUE TITLE
Unable to get metrics into influxdb

### ISSUE THREAD

**Issue by freepenguins** [sensu-extensions/sensu-extensions-influxdb#14]
Followed steps in README, but only getting type=history data in influxdb.

Not seeing any lines from influxdb.rb being written to DB.

Please advise.

**Comment by luisdavim** [comment]
You might be affected by the issue that I'm fixing with #15 can you share your configuration? The extension's configuration and the configuration of the check that is generating the metrics?
Do you have any log entries that you can share?

**Comment by freepenguins** [comment]
/etc/sensu/conf.d/influxdb.json
```
{
    "influxdb": {
        "database": "sensu",
        "host": "localhost",
        "username": "sensu",
        "password": "sensu",
        "port": 8086,
        "tags": {
            "region": "us-east01",
            "stage": "prod"
        },
        "use_ssl": false,
        "strip_metric": "host",
        "templates": [
            {"^sensu\\.checks\\..*":"host.measurement.field*"}
        ]
    }
}
```
/etc/sensu/conf.d/extensions/influxdb.json
```
{
    "extensions": {
        "history": {
            "gem": "sensu-extensions-history"
        },
        "influxdb": {
            "gem": "sensu-extensions-influxdb"
        }
    }
}
```
/etc/sensu/conf.d/checks/metrics-netif.json
```
{
    "checks": {
        "metrics-netif": {
            "command": "/opt/sensu/embedded/bin/metrics-netif.rb",
            "handlers": [
                "default"
            ],
            "interval": 60,
            "standalone": true,
            "subscribers": [
                "ALL"
            ]
        }
    }
}
```
/etc/sensu/conf.d/handlers/default.json
```
{
  "handlers": {
    "default": {
      "command": "true",
      "type": "set",
      "filters": [

      ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "handlers": [
        "metrics" 
      ],
      "handle_flapping": false,
      "handle_silenced": false
    }
  }
}
```
/etc/sensu/conf.d/handlers/metrics.json 
```
{
  "handlers": {
    "metrics": {
      "command": "true",
      "type": "set",
      "filters": [

      ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ],
      "handlers": [
        "debug",
        "influxdb"
      ],
      "handle_flapping": false,
      "handle_silenced": false
    }
  }
}
```
/var/log/sensu/sensu-server.log
```
{"timestamp":"2017-09-18T15:52:07.267692+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/extensions/influxdb.json"}
{"timestamp":"2017-09-18T15:52:07.267741+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/extensions/influxdb.json","changes":{"extensions":{"influxdb":[null,{"gem":"sensu-extensions-influxdb"}],"history":[null,{"gem":"sensu-extensions-history"}]}}}
{"timestamp":"2017-09-18T15:52:07.339555+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2017-09-18T15:52:07.339644+0000","level":"warn","message":"loading extension gem","gem":"sensu-extensions-influxdb","version":null}
{"timestamp":"2017-09-18T15:52:07.339683+0000","level":"warn","message":"requiring extension gem","require":"sensu/extensions/influxdb"}                                        
{"timestamp":"2017-09-18T15:52:07.339719+0000","level":"warn","message":"loading extension gem","gem":"sensu-extensions-history","version":null}
{"timestamp":"2017-09-18T15:52:07.339755+0000","level":"warn","message":"requiring extension gem","require":"sensu/extensions/history"}
{"timestamp":"2017-09-18T15:52:07.339791+0000","level":"warn","message":"loaded extension","type":"bridge","name":"history","description":"Sends check result data to influxdb"}
{"timestamp":"2017-09-18T15:52:07.339827+0000","level":"warn","message":"loaded extension","type":"filter","name":"check_dependencies","description":"filter events when an event exists for a check dependency"}
{"timestamp":"2017-09-18T15:52:07.339863+0000","level":"warn","message":"loaded extension","type":"filter","name":"occurrences","description":"filter events using event occurrences"}
{"timestamp":"2017-09-18T15:52:07.339899+0000","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2017-09-18T15:52:07.339939+0000","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2017-09-18T15:52:07.339977+0000","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2017-09-18T15:52:07.340016+0000","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2017-09-18T15:52:07.340052+0000","level":"warn","message":"loaded extension","type":"handler","name":"influxdb","description":"Outputs metrics to InfluxDB"}
{"timestamp":"2017-09-18T15:52:07.340118+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2017-09-18T15:52:07.340154+0000","level":"debug","message":"setting eventmachine threadpool size","size":22}
{"timestamp":"2017-09-18T15:52:07.340361+0000","level":"debug","message":"connecting to redis","settings":{"port":6379,"host":"127.0.0.1","reconnect_on_error":true,"db":0,"auto_reconnect":true}}                                 
{"timestamp":"2017-09-18T15:52:07.340771+0000","level":"debug","message":"connecting to transport","name":"rabbitmq","settings":{"port":5672,"host":"localhost","user":"sensu","password":"sensu","vhost":"/sensu","heartbeat":30,"prefetch":1}}
{"timestamp":"2017-09-18T15:52:07.383157+0000","level":"info","message":"InfluxDB history extension initialiazed using http://localhost:8086 - Defaults : db=sensu precision=s"}
{"timestamp":"2017-09-18T15:52:07.383263+0000","level":"info","message":"History write buffer initiliazed : buffer flushed every 500 points OR every 6 seconds) "}
{"timestamp":"2017-09-18T15:52:07.383652+0000","level":"info","message":"InfluxDB extension initialiazed using http://localhost:8086 - Defaults : db=sensu precision=s"}
{"timestamp":"2017-09-18T15:52:07.384284+0000","level":"info","message":"InfluxDB write buffer initiliazed : buffer flushed every 500 points OR every 6 seconds) "}
{"timestamp":"2017-09-18T15:52:07.389673+0000","level":"debug","message":"transport connection open"}

... snippet ...

{"timestamp":"2017-09-19T14:46:23.191872+0000","level":"debug","message":"received result","result":{"client":"sensu.domain","check":{"command":"/opt/sensu/embedded/bin/metrics-netif.rb","handlers":["default"],"interval":60,"standalone":true,"subscribers":["ALL"],"name":"metrics-netif","issued":1505832382,"executed":1505832382,"duration":1.076,"output":"sensu.lo.rx_kB_per_sec 0.0 1505832383\nsensu.lo.tx_kB_per_sec 0.0 1505832383\nsensu.eth0.rx_kB_per_sec 0.18 1505832383\nsensu.eth0.tx_kB_per_sec 0.0 1505832383\n","status":0}}}
{"timestamp":"2017-09-19T14:46:23.191975+0000","level":"debug","message":"processing result","result":{"client":"sensu.domain","check":{"command":"/opt/sensu/embedded/bin/metrics-netif.rb","handlers":["default"],"interval":60,"standalone":true,"subscribers":["ALL"],"name":"metrics-netif","issued":1505832382,"executed":1505832382,"duration":1.076,"output":"sensu.lo.rx_kB_per_sec 0.0 1505832383\nsensu.lo.tx_kB_per_sec 0.0 1505832383\nsensu.eth0.rx_kB_per_sec 0.18 1505832383\nsensu.eth0.tx_kB_per_sec 0.0 1505832383\n","status":0}}}
{"timestamp":"2017-09-19T14:46:23.192281+0000","level":"debug","message":"storing check result","check":{"command":"/opt/sensu/embedded/bin/metrics-netif.rb","handlers":["default"],"interval":60,"standalone":true,"subscribers":["ALL"],"name":"metrics-netif","issued":1505832382,"executed":1505832382,"duration":1.076,"output":"sensu.lo.rx_kB_per_sec 0.0 1505832383\nsensu.lo.tx_kB_per_sec 0.0 1505832383\nsensu.eth0.rx_kB_per_sec 0.18 1505832383\nsensu.eth0.tx_kB_per_sec 0.0 1505832383\n","status":0,"type":"standard"}}
{"timestamp":"2017-09-19T14:46:23.193053+0000","level":"debug","message":"bridge extension output","extension":{"type":"extension","name":"history"},"output":"sensu.checks.metrics-netif,type=history,host=sensu.domain value=0 1505832382"}
{"timestamp":"2017-09-19T14:46:26.842948+0000","level":"info","message":"Flushing Buffer"}
```
/var/log/syslog
```
Sep 19 14:46:26 sensu influxd[32637]: [I] 2017-09-19T14:46:26Z Write body received by handler: sensu.checks.metrics-netif,type=history,host=sensu.domain value=0 1505832382 service=httpd
Sep 19 14:46:26 sensu influxd[32637]: [httpd] 127.0.0.1 - sensu [19/Sep/2017:14:46:26 +0000] "POST /write?db=sensu&p=%5BREDACTED%5D&precision=s&u=sensu HTTP/1.1" 204 0 "-" "Event Machine HttpClient" 50988ed5-9d49-11e7-a36b-000000000000 2835
```

**Comment by luisdavim** [comment]
shouldn't you be using the `metrics` handler instead of the `default` in your check configuration?

**Comment by freepenguins** [comment]
The default handler sets metrics.

**Comment by luisdavim** [comment]
You're right,  sorry I missed that.  I think the problem is that in your check you should be setting type metric. 
https://sensuapp.org/docs/latest/reference/checks.html#check-attributes

**Comment by freepenguins** [comment]
I added that to the check and it did not change the behavior.
```
{"timestamp":"2017-09-19T18:51:19.847236+0000","level":"debug","message":"received result","result":{"client":"sensu.domain","check":{"command":"/opt/sensu/embedded/bin/metrics-netif.rb","handlers":["default","metrics"],"interval":60,"standalone":true,"subscribers":["ALL"],"name":"metrics-netif","issued":1505847078,"executed":1505847078,"duration":1.076,"output":"sensu.lo.rx_kB_per_sec 0.0 1505847079\nsensu.lo.tx_kB_per_sec 0.0 1505847079\nsensu.eth0.rx_kB_per_sec 0.23 1505847079\nsensu.eth0.tx_kB_per_sec 0.0 1505847079\n","status":0}}}
{"timestamp":"2017-09-19T18:51:19.847333+0000","level":"debug","message":"processing result","result":{"client":"sensu.domain","check":{"command":"/opt/sensu/embedded/bin/metrics-netif.rb","handlers":["default","metrics"],"interval":60,"standalone":true,"subscribers":["ALL"],"name":"metrics-netif","issued":1505847078,"executed":1505847078,"duration":1.076,"output":"sensu.lo.rx_kB_per_sec 0.0 1505847079\nsensu.lo.tx_kB_per_sec 0.0 1505847079\nsensu.eth0.rx_kB_per_sec 0.23 1505847079\nsensu.eth0.tx_kB_per_sec 0.0 1505847079\n","status":0}}}
{"timestamp":"2017-09-19T18:51:19.847661+0000","level":"debug","message":"storing check result","check":{"command":"/opt/sensu/embedded/bin/metrics-netif.rb","handlers":["default","metrics"],"interval":60,"standalone":true,"subscribers":["ALL"],"name":"metrics-netif","issued":1505847078,"executed":1505847078,"duration":1.076,"output":"sensu.lo.rx_kB_per_sec 0.0 1505847079\nsensu.lo.tx_kB_per_sec 0.0 1505847079\nsensu.eth0.rx_kB_per_sec 0.23 1505847079\nsensu.eth0.tx_kB_per_sec 0.0 1505847079\n","status":0,"type":"standard"}}
{"timestamp":"2017-09-19T18:51:19.848858+0000","level":"debug","message":"bridge extension output","extension":{"type":"extension","name":"history"},"output":"sensu.checks.metrics-netif,type=history,host=sensu.domain value=0 1505847078"}
{"timestamp":"2017-09-19T18:51:21.134554+0000","level":"info","message":"Flushing Buffer"}

**Comment by freepenguins** [comment]
Sorry, misread what you said. You were correct, I was missing 'type: "metric"' in my checks.

I get this now....
```
{"timestamp":"2017-09-19T19:02:09.224577+0000","level":"info","message":"handler extension output","extension":{"type":"extension","name":"influxdb"},"event":{"id":"9d89f84a-07c9-4dbd-ab82-98e4f337766c"},"output":"TypeError: no implicit conversion of Array into Hash\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-0.0.2/lib/sensu/extensions/influxdb.rb:54:in `merge'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-0.0.2/lib/sensu/extensions/influxdb.rb:54:in `run'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extension-1.5.1/lib/sensu/extension.rb:113:in `safe_run'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/handle.rb:128:in `handler_extension'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/handle.rb:156:in `handler_type_router'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/handle.rb:175:in `handle_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:266:in `block (3 levels) in process_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/mutate.rb:19:in `block in mutator_callback'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extension-1.5.1/lib/sensu/extension.rb:114:in `block in safe_run'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-json-1.0.0/lib/sensu/extensions/json.rb:16:in `run'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extension-1.5.1/lib/sensu/extension.rb:113:in `safe_run'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/mutate.rb:59:in `mutator_extension'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/mutate.rb:82:in `mutate_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:265:in `block (2 levels) in process_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/filter.rb:212:in `block in filter_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/filter.rb:179:in `event_filtered?'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/filter.rb:210:in `filter_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:264:in `block in process_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:262:in `each'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:262:in `process_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:703:in `block (4 levels) in process_check_result'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:526:in `update_event_registry'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:702:in `block (3 levels) in process_check_result'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:586:in `block (3 levels) in create_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:494:in `event_silenced?'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:585:in `block (2 levels) in create_event'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-redis-2.2.0/lib/sensu/redis/client.rb:337:in `dispatch_response'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-redis-2.2.0/lib/sensu/redis/client.rb:357:in `parse_response_line'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-redis-2.2.0/lib/sensu/redis/client.rb:387:in `receive_data'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/lib/sensu/server/process.rb:33:in `run'\n  /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.2/exe/sensu-server:10:in `<top (required)>'\n  /opt/sensu/bin/sensu-server:22:in `load'\n  /opt/sensu/bin/sensu-server:22:in `<main>'","status":2}

**Comment by freepenguins** [comment]
I updated to the latest version of the extension and the error no longer appears and I'm getting metrics.

Thanks for the hard work and prompt reply!

**Comment by luisdavim** [comment]
Awesome. Glad I could help.
