### ISSUE TITLE
[BUG] Failed to require extension

### ISSUE THREAD

**Issue by mdzidic** [sensu-extensions/sensu-extensions-influxdb#6]
Hello,

I've problem with loading this Sensu extension...
_Sensu server v1.0.0_

/etc/sensu/extensions
```
.
|-- history.rb
|-- influxdb
|   `-- influx_relay.rb
`-- influxdb.rb
```
Error log:
```
{"timestamp":"2017-07-13T13:20:24.000844+0000","level":"warn","message":"failed to require extension","file":"/etc/sensu/extensions/influxdb.rb","error":{"path":"sensu/extensions/influxdb/influx_relay","~bt_locations":"#<Thread::Backtrace:0x00000003375b38>","~mesg":"cannot load such file -- sensu/extensions/influxdb/influx_relay","~bt":["/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/etc/sensu/extensions/influxdb.rb:6:in `<top (required)>'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:83:in `load_file'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:99:in `block in load_directory'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:98:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:98:in `load_directory'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:20:in `load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:44:in `get'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/daemon.rb:158:in `load_extensions'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/daemon.rb:58:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:44:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:32:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:32:in `run'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/exe/sensu-server:10:in `<top (required)>'","/opt/sensu/bin/sensu-server:22:in `load'","/opt/sensu/bin/sensu-server:22:in `<main>'"]}}
{"timestamp":"2017-07-13T13:20:24.001009+0000","level":"warn","message":"ignoring extension","file":"/etc/sensu/extensions/influxdb.rb"}
{"timestamp":"2017-07-13T13:20:24.001074+0000","level":"warn","message":"loading extension file","file":"/etc/sensu/extensions/history.rb"}
{"timestamp":"2017-07-13T13:20:24.001166+0000","level":"warn","message":"failed to require extension","file":"/etc/sensu/extensions/history.rb","error":{"path":"sensu/extensions/influxdb/influx_relay","~bt_locations":"#<Thread::Backtrace:0x0000000334de08>","~mesg":"cannot load such file -- sensu/extensions/influxdb/influx_relay","~bt":["/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/etc/sensu/extensions/history.rb:6:in `<top (required)>'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:83:in `load_file'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:99:in `block in load_directory'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:98:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:98:in `load_directory'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:20:in `load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:44:in `get'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/daemon.rb:158:in `load_extensions'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/daemon.rb:58:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:44:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:32:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:32:in `run'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/exe/sensu-server:10:in `<top (required)>'","/opt/sensu/bin/sensu-server:22:in `load'","/opt/sensu/bin/sensu-server:22:in `<main>'"]}}
{"timestamp":"2017-07-13T13:20:24.001262+0000","level":"warn","message":"ignoring extension","file":"/etc/sensu/extensions/history.rb"}
{"timestamp":"2017-07-13T13:20:24.001324+0000","level":"warn","message":"loading extension file","file":"/etc/sensu/extensions/influxdb/influx_relay.rb"}
{"timestamp":"2017-07-13T13:20:24.001385+0000","level":"warn","message":"loading extension file","file":"/etc/sensu/extensions/influxdb/influx_relay.rb"}

```

**Comment by luisdavim** [comment]
hi, I'll take a look at this.

**Comment by luisdavim** [comment]
Hi @mdzidic did you build the gem from the latest master version on this repo?
I can't reproduce that error, I get:
```
{"timestamp":"2017-07-26T09:25:32.567517+0000","level":"warn","message":"loading extension gem","gem":"sensu-extensions-history","version":null}
{"timestamp":"2017-07-26T09:25:32.567535+0000","level":"warn","message":"requiring extension gem","require":"sensu/extensions/history"}
{"timestamp":"2017-07-26T09:25:32.567553+0000","level":"warn","message":"loaded extension","type":"bridge","name":"history","description":"Sends check result data to influxdb"}
{"timestamp":"2017-07-26T09:25:32.567571+0000","level":"warn","message":"loaded extension","type":"filter","name":"occurrences","description":"filter events using event occurrences"}
{"timestamp":"2017-07-26T09:25:32.567590+0000","level":"warn","message":"loaded extension","type":"filter","name":"check_dependencies","description":"filter events when an event exists for a check dependency"}
{"timestamp":"2017-07-26T09:25:32.567617+0000","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2017-07-26T09:25:32.567637+0000","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2017-07-26T09:25:32.567655+0000","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2017-07-26T09:25:32.567672+0000","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2017-07-26T09:25:32.567690+0000","level":"warn","message":"loaded extension","type":"handler","name":"influxdb","description":"Outputs metrics to InfluxDB"}
```

**Comment by luisdavim** [comment]
also, can you share your config for the extension?

**Comment by luisdavim** [comment]
But I'm on sensu 1.0.1:
```
# rpm -qa | grep sensu
sensu-1.0.1-1.el7.x86_64
```
could that be the difference?

**Comment by mdzidic** [comment]
Hello @luisdavim
I've manually downloaded this extension from this repo to my /etc/sensu/extensions

**Comment by luisdavim** [comment]
You mean you downloaded the code and placed it there?
@mdzidic can you try to build the gem:
```
git clone https://github.com/sensu-extensions/sensu-extensions-influxdb.git
cd sensu-extensions-influxdb
bundle install
bundle exec rake
bundle exec rake build
```
 and then install it with:
```
sensu-install -e pkg/sensu-extensions-influxdb-0.0.2.gem
```
and let me know if that solves your problem.

**Comment by mdzidic** [comment]
Hello @luisdavim ,

I'll try that way, I tried to copy /bin to /etc/sensu/extensions as I do for all other extensions...

**Comment by luisdavim** [comment]
cool, please let me know if that fixed the problem.

**Comment by mdzidic** [comment]
Hello,

Sorry for late reply, building gem works for me.
I usually just copy extension files from /bin folder, and I don't know why this time didn't work that way...
